In [76]:
import matplotlib.pyplot as plt
import cv2
from mtcnn import MTCNN
import numpy as np
import math

In [77]:
detector = MTCNN()

In [78]:
Image_path = 'C:\\Users\\PriyankaPrabhu\\FaceDetection\\ImposterRawTestFinal\\face271.jpg'

In [79]:
img = cv2.imread(Image_path)
print(img)

[[[181 198 211]
  [128 145 158]
  [ 82  95 109]
  ...
  [178 197 202]
  [185 204 209]
  [186 205 210]]

 [[128 145 158]
  [ 66  82  95]
  [ 31  44  58]
  ...
  [181 200 205]
  [183 202 207]
  [183 202 207]]

 [[ 91 107 120]
  [ 35  51  64]
  [ 21  35  47]
  ...
  [173 191 198]
  [175 193 200]
  [186 204 211]]

 ...

 [[135 156 154]
  [128 149 147]
  [134 152 151]
  ...
  [ 29  33  38]
  [ 28  33  36]
  [ 28  33  36]]

 [[139 160 158]
  [132 153 151]
  [137 155 154]
  ...
  [ 30  33  38]
  [ 28  33  36]
  [ 28  33  36]]

 [[137 158 156]
  [134 155 153]
  [137 155 154]
  ...
  [ 29  32  36]
  [ 28  33  36]
  [ 28  33  36]]]


In [80]:
img_cpy = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

In [81]:
cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

array([[[211, 198, 181],
        [158, 145, 128],
        [109,  95,  82],
        ...,
        [202, 197, 178],
        [209, 204, 185],
        [210, 205, 186]],

       [[158, 145, 128],
        [ 95,  82,  66],
        [ 58,  44,  31],
        ...,
        [205, 200, 181],
        [207, 202, 183],
        [207, 202, 183]],

       [[120, 107,  91],
        [ 64,  51,  35],
        [ 47,  35,  21],
        ...,
        [198, 191, 173],
        [200, 193, 175],
        [211, 204, 186]],

       ...,

       [[154, 156, 135],
        [147, 149, 128],
        [151, 152, 134],
        ...,
        [ 38,  33,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[158, 160, 139],
        [151, 153, 132],
        [154, 155, 137],
        ...,
        [ 38,  33,  30],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[156, 158, 137],
        [153, 155, 134],
        [154, 155, 137],
        ...,
        [ 36,  32,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]]

In [82]:
detections = detector.detect_faces(img_cpy)

In [83]:
detections

[{'box': [0, 6, 110, 139],
  'confidence': 0.9988126754760742,
  'keypoints': {'left_eye': (31, 63),
   'right_eye': (83, 58),
   'nose': (59, 88),
   'mouth_left': (44, 119),
   'mouth_right': (84, 115)}}]

In [84]:
confidence = 0
for det in detections:
    if(det['confidence'] > confidence):
        keypoints = det['keypoints']
#cv2.circle(img_cpy, keypoints['left_eye'], 2, (255, 0, 0) , 2)
#cv2.circle(img_cpy, keypoints['right_eye'], 2, (255, 0, 0) , 2)
cv2.line(img_cpy,keypoints['right_eye'], keypoints['left_eye'],(67,67,67),2)

array([[[211, 198, 181],
        [158, 145, 128],
        [109,  95,  82],
        ...,
        [202, 197, 178],
        [209, 204, 185],
        [210, 205, 186]],

       [[158, 145, 128],
        [ 95,  82,  66],
        [ 58,  44,  31],
        ...,
        [205, 200, 181],
        [207, 202, 183],
        [207, 202, 183]],

       [[120, 107,  91],
        [ 64,  51,  35],
        [ 47,  35,  21],
        ...,
        [198, 191, 173],
        [200, 193, 175],
        [211, 204, 186]],

       ...,

       [[154, 156, 135],
        [147, 149, 128],
        [151, 152, 134],
        ...,
        [ 38,  33,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[158, 160, 139],
        [151, 153, 132],
        [154, 155, 137],
        ...,
        [ 38,  33,  30],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[156, 158, 137],
        [153, 155, 134],
        [154, 155, 137],
        ...,
        [ 36,  32,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]]

In [85]:
cv2.imshow("Image",img_cpy)
cv2.waitKey(0)

-1

In [86]:
left_eye = keypoints['left_eye']
right_eye = keypoints['right_eye']

In [120]:
if left_eye[1] < right_eye[1]:
    direction = 1
    third_point = (left_eye[0], right_eye[1])
else:
    direction = -1
    third_point = (right_eye[0], left_eye[1])

In [121]:
cv2.circle(img_cpy, third_point, 2, (255, 0, 0) , 2)

array([[[211, 198, 181],
        [158, 145, 128],
        [109,  95,  82],
        ...,
        [202, 197, 178],
        [209, 204, 185],
        [210, 205, 186]],

       [[158, 145, 128],
        [ 95,  82,  66],
        [ 58,  44,  31],
        ...,
        [205, 200, 181],
        [207, 202, 183],
        [207, 202, 183]],

       [[120, 107,  91],
        [ 64,  51,  35],
        [ 47,  35,  21],
        ...,
        [198, 191, 173],
        [200, 193, 175],
        [211, 204, 186]],

       ...,

       [[154, 156, 135],
        [147, 149, 128],
        [151, 152, 134],
        ...,
        [ 38,  33,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[158, 160, 139],
        [151, 153, 132],
        [154, 155, 137],
        ...,
        [ 38,  33,  30],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[156, 158, 137],
        [153, 155, 134],
        [154, 155, 137],
        ...,
        [ 36,  32,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]]

In [122]:
cv2.imshow("Image",img_cpy)
cv2.waitKey(0)

-1

In [123]:
print(direction)

-1


In [124]:
cv2.line(img_cpy, left_eye, third_point, (67, 67, 67), 2)
cv2.line(img_cpy, right_eye, third_point, (67, 67, 67), 2)

array([[[211, 198, 181],
        [158, 145, 128],
        [109,  95,  82],
        ...,
        [202, 197, 178],
        [209, 204, 185],
        [210, 205, 186]],

       [[158, 145, 128],
        [ 95,  82,  66],
        [ 58,  44,  31],
        ...,
        [205, 200, 181],
        [207, 202, 183],
        [207, 202, 183]],

       [[120, 107,  91],
        [ 64,  51,  35],
        [ 47,  35,  21],
        ...,
        [198, 191, 173],
        [200, 193, 175],
        [211, 204, 186]],

       ...,

       [[154, 156, 135],
        [147, 149, 128],
        [151, 152, 134],
        ...,
        [ 38,  33,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[158, 160, 139],
        [151, 153, 132],
        [154, 155, 137],
        ...,
        [ 38,  33,  30],
        [ 36,  33,  28],
        [ 36,  33,  28]],

       [[156, 158, 137],
        [153, 155, 134],
        [154, 155, 137],
        ...,
        [ 36,  32,  29],
        [ 36,  33,  28],
        [ 36,  33,  28]]

In [125]:
def euclidean_distance(a, b):
    x1 = a[0]; y1 = a[1]
    x2 = b[0]; y2 = b[1]
    return math.sqrt(((x2 - x1) * (x2 - x1)) + ((y2 - y1) * (y2 - y1)))

In [126]:
a = euclidean_distance(left_eye, third_point)
b = euclidean_distance(right_eye, third_point)
c = euclidean_distance(left_eye, right_eye)
print(a, b, c)

52.0 5.0 52.23983154643591


In [141]:
cosine_rule = (c*c + a*a - b*b)/(2*a*c)
print(cosine_rule)

0.9954090291002811


In [142]:
angle_radian = np.arccos(cosine_rule)

In [143]:
print(angle_radian)

0.09585914711001343


In [144]:
final_angle = angle_radian * 180/math.pi

In [145]:
if(direction == 1):
    final_angle = 90 - final_angle

In [146]:
final_angle

5.492324557127452

In [147]:
from PIL import Image
new_img = Image.fromarray(img_cpy)
new_img = np.array(new_img.rotate(direction * final_angle))

In [148]:
cv2.imshow('ff', new_img)
cv2.waitKey(0)

-1